// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QlySukienSV.Data;

#nullable disable

namespace QlySukienSV.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251114040651_UpdateModel")]
    partial class UpdateModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QlySukienSV.Models.CLB", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChuNhiemId")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayThanhLap")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenCLB")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("ChuNhiemId");

                    b.ToTable("CLBs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ChuNhiemId = 2,
                            MoTa = "Hỗ trợ cộng đồng và tổ chức các chiến dịch tình nguyện.",
                            NgayThanhLap = new DateTime(2018, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenCLB = "CLB Tình nguyện Xanh",
                            TrangThai = "Active"
                        },
                        new
                        {
                            Id = 2,
                            ChuNhiemId = 3,
                            MoTa = "Nơi chia sẻ kiến thức, tổ chức workshop công nghệ.",
                            NgayThanhLap = new DateTime(2019, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenCLB = "CLB Công nghệ",
                            TrangThai = "Active"
                        },
                        new
                        {
                            Id = 3,
                            ChuNhiemId = 4,
                            MoTa = "Các hoạt động về âm nhạc, nhảy và nghệ thuật.",
                            NgayThanhLap = new DateTime(2017, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenCLB = "CLB Nghệ thuật",
                            TrangThai = "Active"
                        });
                });

            modelBuilder.Entity("QlySukienSV.Models.DangKySuKien", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("NguoiDungId")
                        .HasColumnType("int");

                    b.Property<int>("SuKienId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ThoiGianDangKy")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("NguoiDungId");

                    b.HasIndex("SuKienId");

                    b.ToTable("DangKySuKiens");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            NguoiDungId = 3,
                            SuKienId = 1,
                            ThoiGianDangKy = new DateTime(2025, 1, 5, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            TrangThai = "DaDuyet"
                        },
                        new
                        {
                            Id = 2,
                            NguoiDungId = 4,
                            SuKienId = 2,
                            ThoiGianDangKy = new DateTime(2025, 1, 10, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            TrangThai = "ChoDuyet"
                        });
                });

            modelBuilder.Entity("QlySukienSV.Models.DiemDanhSuKien", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("HinhThuc")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("NguoiDungId")
                        .HasColumnType("int");

                    b.Property<int>("SuKienId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ThoiGianDiemDanh")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("NguoiDungId");

                    b.HasIndex("SuKienId");

                    b.ToTable("DiemDanhSuKiens");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            HinhThuc = "QR",
                            NguoiDungId = 3,
                            SuKienId = 1,
                            ThoiGianDiemDanh = new DateTime(2025, 6, 1, 8, 15, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("QlySukienSV.Models.NguoiDung", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Lop")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MaSoSV")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("NguoiDungs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@gmail.com",
                            HoTen = "Quản trị viên",
                            MatKhau = "$2a$11$abcdefghijklmnopqrstuu57/Uc/xTpWqycuFrOG98xEU9RAuvm36",
                            RoleId = 1,
                            SoDienThoai = "0911000000"
                        },
                        new
                        {
                            Id = 2,
                            Email = "bch001@gmail.com",
                            HoTen = "Ban chấp hành",
                            Lop = "QLCL",
                            MatKhau = "$2a$11$abcdefghijklmnopqrstuu57/Uc/xTpWqycuFrOG98xEU9RAuvm36",
                            RoleId = 2,
                            SoDienThoai = "0911000001"
                        },
                        new
                        {
                            Id = 3,
                            Email = "sv001@gmail.com",
                            HoTen = "Nguyễn Văn A",
                            Lop = "CNTT K45",
                            MaSoSV = "SV001",
                            MatKhau = "$2a$11$abcdefghijklmnopqrstuu57/Uc/xTpWqycuFrOG98xEU9RAuvm36",
                            RoleId = 3,
                            SoDienThoai = "0911000002"
                        },
                        new
                        {
                            Id = 4,
                            Email = "sv002@gmail.com",
                            HoTen = "Trần Thị B",
                            Lop = "CNTT K45",
                            MaSoSV = "SV002",
                            MatKhau = "$2a$11$abcdefghijklmnopqrstuu57/Uc/xTpWqycuFrOG98xEU9RAuvm36",
                            RoleId = 3,
                            SoDienThoai = "0911000003"
                        },
                        new
                        {
                            Id = 5,
                            Email = "sv003@gmail.com",
                            HoTen = "Lê Văn C",
                            Lop = "KinhTe K46",
                            MaSoSV = "SV003",
                            MatKhau = "$2a$11$abcdefghijklmnopqrstuu57/Uc/xTpWqycuFrOG98xEU9RAuvm36",
                            RoleId = 3,
                            SoDienThoai = "0911000004"
                        });
                });

            modelBuilder.Entity("QlySukienSV.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MoTa")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TenRole")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("TenRole")
                        .IsUnique();

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MoTa = "Quản trị viên hệ thống",
                            TenRole = "QuanTri"
                        },
                        new
                        {
                            Id = 2,
                            MoTa = "Ban chấp hành Đoàn/Hội SV",
                            TenRole = "BanChapHanh"
                        },
                        new
                        {
                            Id = 3,
                            MoTa = "Sinh viên",
                            TenRole = "SinhVien"
                        },
                        new
                        {
                            Id = 4,
                            MoTa = "Giảng viên",
                            TenRole = "GiangVien"
                        });
                });

            modelBuilder.Entity("QlySukienSV.Models.SuKien", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CLBId")
                        .HasColumnType("int");

                    b.Property<string>("DiaDiem")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("NoiBat")
                        .HasColumnType("bit");

                    b.Property<string>("TenSuKien")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("CLBId");

                    b.ToTable("SuKiens");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CLBId = 1,
                            DiaDiem = "Hội trường ABC",
                            MoTa = "Chiến dịch tình nguyện tại các tỉnh miền Trung.",
                            NgayBatDau = new DateTime(2025, 6, 1, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            NgayKetThuc = new DateTime(2025, 6, 5, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            NoiBat = true,
                            TenSuKien = "Chiến dịch mùa hè xanh",
                            TrangThai = "HoanThanh"
                        },
                        new
                        {
                            Id = 2,
                            CLBId = 2,
                            DiaDiem = "Phòng Lab 301",
                            MoTa = "Tọa đàm về xu hướng AI và Cloud.",
                            NgayBatDau = new DateTime(2025, 2, 15, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            NgayKetThuc = new DateTime(2025, 2, 15, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            NoiBat = true,
                            TenSuKien = "Tech Talk 2025",
                            TrangThai = "HoanThanh"
                        },
                        new
                        {
                            Id = 3,
                            CLBId = 3,
                            DiaDiem = "Sân khấu B",
                            MoTa = "Chương trình văn nghệ mừng năm mới.",
                            NgayBatDau = new DateTime(2025, 1, 20, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            NgayKetThuc = new DateTime(2025, 1, 20, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            NoiBat = false,
                            TenSuKien = "Đêm nghệ thuật Xuân",
                            TrangThai = "HoanThanh"
                        });
                });

            modelBuilder.Entity("QlySukienSV.Models.ThanhVienCLB", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CLBId")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayThamGia")
                        .HasColumnType("datetime2");

                    b.Property<int>("NguoiDungId")
                        .HasColumnType("int");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("CLBId");

                    b.HasIndex("NguoiDungId");

                    b.ToTable("ThanhVienCLBs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CLBId = 1,
                            NgayThamGia = new DateTime(2018, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NguoiDungId = 2,
                            TrangThai = "DaDuyet",
                            VaiTro = "ChuNhiem"
                        },
                        new
                        {
                            Id = 2,
                            CLBId = 1,
                            NgayThamGia = new DateTime(2023, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NguoiDungId = 3,
                            TrangThai = "DaDuyet",
                            VaiTro = "ThanhVien"
                        },
                        new
                        {
                            Id = 3,
                            CLBId = 2,
                            NgayThamGia = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NguoiDungId = 3,
                            TrangThai = "DaDuyet",
                            VaiTro = "BanChapHanh"
                        },
                        new
                        {
                            Id = 4,
                            CLBId = 2,
                            NgayThamGia = new DateTime(2019, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NguoiDungId = 4,
                            TrangThai = "DaDuyet",
                            VaiTro = "ChuNhiem"
                        },
                        new
                        {
                            Id = 5,
                            CLBId = 3,
                            NgayThamGia = new DateTime(2017, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NguoiDungId = 5,
                            TrangThai = "DaDuyet",
                            VaiTro = "ChuNhiem"
                        });
                });

            modelBuilder.Entity("QlySukienSV.Models.CLB", b =>
                {
                    b.HasOne("QlySukienSV.Models.NguoiDung", "ChuNhiem")
                        .WithMany()
                        .HasForeignKey("ChuNhiemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChuNhiem");
                });

            modelBuilder.Entity("QlySukienSV.Models.DangKySuKien", b =>
                {
                    b.HasOne("QlySukienSV.Models.NguoiDung", "NguoiDung")
                        .WithMany("DangKySuKiens")
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QlySukienSV.Models.SuKien", "SuKien")
                        .WithMany("DangKySuKiens")
                        .HasForeignKey("SuKienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");

                    b.Navigation("SuKien");
                });

            modelBuilder.Entity("QlySukienSV.Models.DiemDanhSuKien", b =>
                {
                    b.HasOne("QlySukienSV.Models.NguoiDung", "NguoiDung")
                        .WithMany("DiemDanhSuKiens")
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QlySukienSV.Models.SuKien", "SuKien")
                        .WithMany("DiemDanhSuKiens")
                        .HasForeignKey("SuKienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");

                    b.Navigation("SuKien");
                });

            modelBuilder.Entity("QlySukienSV.Models.NguoiDung", b =>
                {
                    b.HasOne("QlySukienSV.Models.Role", "Role")
                        .WithMany("NguoiDungs")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("QlySukienSV.Models.SuKien", b =>
                {
                    b.HasOne("QlySukienSV.Models.CLB", "CLB")
                        .WithMany("SuKiens")
                        .HasForeignKey("CLBId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CLB");
                });

            modelBuilder.Entity("QlySukienSV.Models.ThanhVienCLB", b =>
                {
                    b.HasOne("QlySukienSV.Models.CLB", "CLB")
                        .WithMany("ThanhViens")
                        .HasForeignKey("CLBId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QlySukienSV.Models.NguoiDung", "NguoiDung")
                        .WithMany("ThanhVienCLBs")
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CLB");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("QlySukienSV.Models.CLB", b =>
                {
                    b.Navigation("SuKiens");

                    b.Navigation("ThanhViens");
                });

            modelBuilder.Entity("QlySukienSV.Models.NguoiDung", b =>
                {
                    b.Navigation("DangKySuKiens");

                    b.Navigation("DiemDanhSuKiens");

                    b.Navigation("ThanhVienCLBs");
                });

            modelBuilder.Entity("QlySukienSV.Models.Role", b =>
                {
                    b.Navigation("NguoiDungs");
                });

            modelBuilder.Entity("QlySukienSV.Models.SuKien", b =>
                {
                    b.Navigation("DangKySuKiens");

                    b.Navigation("DiemDanhSuKiens");
                });
#pragma warning restore 612, 618
        }
    }
}
